### ISSUE TITLE
Withdraw 

### ISSUE THREAD

**Issue by vpavlikk** [openware/peatio#2084] opened 2019-02-21 11:10 UTC
I can reject withdraw from admin panel when it has already appeared in blockchain

**Comment by endofthepain** [comment] 2019-02-21 11:53
no you cant because your transaction has appeared in blockchain

**Comment by shal** [comment] 2019-02-21 13:03
@vpavlikk Could you send us video/photo approval of this bug please?

**Comment by vpavlikk** [comment] 2019-02-21 14:24
https://streamable.com/eggqu
https://streamable.com/g57w5

**Comment by martianatwork** [comment] 2019-03-24 09:48
@shal i can confirm that this bug is present, 
The issue is here:
https://github.com/rubykube/peatio/blob/e0cc1f0f4f3c1b97cc70a35bb34f3f21695a3908/app/models/withdraw.rb#L82

Withdraws with confirming status should not be rejected.
it may make sense for fiat but not for crypto.

**Comment by ysv** [comment] 2019-04-03 14:01
closed in #2135

**Closed as completed by ysv** 2019-04-03 14:01 UTC
Labels: Type: Bug, Needs discussion
