### ISSUE TITLE
Ability to block regular users to access the UI

### ISSUE THREAD

**Issue by calj** [openware/peatio#563] opened 2018-02-21 09:33 UTC
Regular users should have access to market page and API only.
We will still need the admin to access the UI (maybe /admin only).

**Comment by yivo** [comment] 2018-02-21 09:37
Duplicate of https://github.com/rubykube/peatio/issues/521. 

PR is ready and tested: https://github.com/rubykube/peatio/pull/534

**Closed as completed by yivo** 2018-02-21 09:37 UTC
