### ISSUE TITLE
USD markets list is empty

### ISSUE THREAD

**Issue by fansyfs** [openware/peatio#482] opened 2018-02-08 09:55 UTC
<img width="401" alt="untitled" src="https://user-images.githubusercontent.com/538516/35966554-0f3a53c8-0cf9-11e8-99f0-06a059d75fad.png">
<img width="425" alt="untitled 2" src="https://user-images.githubusercontent.com/538516/35966560-13587160-0cf9-11e8-8cac-69233f3e12f9.png">

**Comment by yivo** [comment] 2018-02-08 10:45
Duplicate of https://github.com/rubykube/peatio/issues/460.

**Closed as completed by yivo** 2018-02-08 10:45 UTC
Labels: Type: Question
