### ISSUE TITLE
User should not be able to focus disabled fields when editing proof

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#186] opened 2017-12-22 18:37 UTC
Click on button "Edit":

1. We can edit "Created at"  
![screen shot 2017-12-21 at 8 10 27 pm](https://user-images.githubusercontent.com/29736025/34308898-040a3ebc-e758-11e7-94e3-e19bbdad3320.png)

2. We can edit choose another currency 

Changes are not applying

**Comment by yivo** [comment] 2017-12-26 11:17
@mkuvshynnikov You can edit only "Balance" field. The rest fields are marked as "disabled" (that's why they have grey BG). The problem is that fields can be focused ever they are disabled. We need to fix it.

**Closed as completed** 2017-12-27 10:07 UTC
Labels: Type: Bug
