### ISSUE TITLE
New currencies not displayed for old users

### ISSUE THREAD

**Issue by calj** [openware/peatio#447] opened 2018-02-05 11:40 UTC
In the case of deployment of new currencies on an existing platform, new currencies are not listed for existing users, only new user see them.

**Comment by tzman89** [comment] 2018-02-05 11:50
This is already posted multiple times,until it's fixed you can run: 
bundle exec rails r "Member.find_each(&:touch_accounts)"

set cronjob for it and it should work

**Comment by yivo** [comment] 2018-02-05 12:06
Duplicate of #436.

**Closed as completed by yivo** 2018-02-05 12:06 UTC
Labels: Type: Bug
