### ISSUE TITLE
markets not working.

### ISSUE THREAD

**Issue by nantestdeveloper** [openware/peatio#779] opened 2018-04-04 12:04 UTC
run peatio on local ubuntu 
markets not working

url   http://localhost:3000/trading/btcusd
showing error       Routing Error
The URL you requested was not found.

Is the matser branch is stable?

**Comment by yivo** [comment] 2018-04-04 12:09
Duplicate of https://github.com/rubykube/peatio/issues/738

**Closed as completed** 2018-04-04 12:09 UTC
Labels: Type: Question
